#+ summary: Every Indian Affairs agent ever posted to Battleford
#+ endpoint: https://fuseki.lincsproject.ca/lincs/sparql

PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX event: <http://id.lincsproject.ca/event/>

SELECT DISTINCT ?agentName ?role ?begin ?end WHERE {
  GRAPH <http://graph.lincsproject.ca/hist-canada/ind-affairs> {
    ?place rdfs:label "Battleford" .
    ?occ a crm:E7_Activity ;
         crm:P7_took_place_at ?place ;
         crm:P14_carried_out_by ?agent ;
         crm:P2_has_type event:OccupationEvent ;
         rdfs:label ?role ;
         crm:P4_has_time-span ?ts .
    ?agent rdfs:label ?agentName .
    ?ts crm:P82a_begin_of_the_begin ?begin .
    OPTIONAL { ?ts crm:P82b_end_of_the_end ?end . }
  }
}
ORDER BY ?begin ?agentName
